version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Docker/"
    schedule:
      interval: "daily"
    labels:
      - '📦 Dependencies'
      - '🐍 Python'
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - '📦 Dependencies'
      - '🐍 Python'
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'daily'
    labels:
      - '📦 Dependencies'
      - '🚀 CI/CD'
