settings:
  description: Manage your Github repo(s) settings and secrets using Github Actions and a yaml file
  homepage: https://github.com/actuarysailor/gha-repo-manager

  topics:
   - github-actions
   - python

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  # has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    description: Bug identified
    color: F4D03F # d73a4a
    new_name: 🐞 Bug

  - name: documentation
    description: Improvements or additions to documentation
    color: 228AFF # 0075ca
    new_name: 📝 Documentation

  - name: duplicate
    description: This issue or pull request already exists
    color: 17202A # cfd3d7
    new_name: 💩 Duplicate

  - name: enhancement
    description: Feature added in the PR
    color: F10505 # a2eeef
    new_name: ✅ Feature

  - name: 'good first issue'
    description: Good for newcomers
    color: 7057ff
    new_name: 👶 Good First Issue

  - name: 'help wanted'
    description: Extra attention is needed
    color: 008672
    new_name: 🆘 Help Wanted

  - name: invalid
    description: This doesn't seem right
    color: e4e669
    new_name: 🚫 Invalid

  - name: question
    description: Further information is requested
    color: d876e3
    new_name: ❓ Question

  - name: wontfix
    description: This will not be worked on
    color: ffffff
    new_name: 🙅‍♂️ Wontfix

  - name: ⚠️ Breaking Change
    description: Breaking change in the PR
    color: F1F800

  - name: 🐳 Build
    description: Indicates the change is related to the build
    color: 0FD4DA

  - name: 🚀 CI/CD
    description: Indicates the change is related to CI/CD workflows
    color: FF4D4D

  - name: ⚙️ Configuration
    description: Indicates the scope is related to the configuration
    color: BDBDBD

  - name: 📦 Dependencies
    description: Pull requests that update a dependency file
    color: 95A5A6

  - name: 👀 Feature Requested
    description: Request for a feature
    color: 07D90A

  - name: 🕵🏻 Fix
    description: Fix applied in the PR
    color: F4D03F

  - name: 🔧 Github Configuration
    description: Indicates the change is related to github settings
    color: '555555'

  - name: 💻 Source
    description: Indicates the scope is related to the own service logic
    color: FDC720

  - name: 🧪 Tests
    description: Indicates the scope is related to the tests
    color: 088E26

  - name: 🤩 size/xs
    description: Pull request size XS
    color: 27AE60

  - name: 🥳 size/s
    description: Pull request size S
    color: 2ECC71

  - name: 😎 size/m
    description: Pull request size M
    color: F1C40F

  - name: 😖 size/l
    description: Pull request size L
    color: F39C12

  - name: 🤯 size/xl
    description: Pull request size XL
    color: E67E22

  - name: ignore-for-release
    description: Ignore pull request for a new release
    color: 9C28FC

  - name: 'autorelease: tagged'
    description: Used by release-please to indicate a release has been tagged
    color: EDEDED

  - name: 'autorelease: pending'
    description: Used by release-please to indicate a release is pending
    color: EDEDED

branch_protections:
  - name: main

    protection:
      pr_options:

        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        checks:
          - pre-commit 3.11 / ubuntu-latest
          - Action Integration Status
          - Generate Docs
      enforce_admins: false
      allow_force_pushes: true
