settings:
  description: Manage your Github repo(s) settings and secrets using Github Actions and a yaml file
  homepage: https://github.com/actuarysailor/gha-repo-manager

  topics:
   - github-actions
   - python

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  # has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system.

  - name: feature
    color: '#336699'
    description: New functionality.

branch_protections:
  - name: main

    protection:
      pr_options:

        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        checks:
          - pre-commit 3.11 / ubuntu-latest
          - Action Integration Testing
          - Generate Docs
      enforce_admins: false
      allow_force_pushes: true
