exclude: ".*tests\/fixtures.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
      - id: trailing-whitespace
        stages: [pre-commit, pre-push, manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.0
    hooks:
      - id: actionlint
        name: Actionlint
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
  - repo: local
    hooks:
      - id: update-inputs
        name: Update inputs
        entry: make generate-inputs
        language: system
        pass_filenames: false
