collaborators:
  - name: andrewthetechie
    type: user
    permission: pull
    exists: false

settings:
  description: This repo is for testing github actions against without messing up a real repo
  homepage: ""
  topics: ""
  private: true
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: first-timers-only
    new_name: Help Wanted

  - name: Fake Label
    exists: false

branch_protections:
  - name: main
    protection:
      exists: false

environments:
  - name: production
    exists: false
    secrets:
      - key: PRODUCTION_SECRET
        type: environments/production
        exists: false
    variables:
      - key: PROD_VARIABLE
        type: environments/production
        exists: false

secrets:
  - key: SECRET_KEY
    exists: false
  - key: SECRET_KEY
    exists: false
  - key: ANOTHER_SECRET
    exists: false
  - key: THIRD_SECRET
    exists: false

variables:
  - key: VARIABLE1
    exists: false
