# Tests athe github action on each push
name: Action Integration Test
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/action-integration.yml'
      - 'action.yml'
      - 'Dockerfile'
      - '**/*.py'

  pull_request_target:
    paths:
      - '.github/workflows/action-integration.yml'
      - 'action.yml'
      - 'Dockerfile'
      - '**/*.py'

jobs:
  strategy:
    matrix:
      include:
      - repo: self
        action: check
        settings_file: '[".github/settings.yml"]'
        fail_on_diff: true
      - repo: actuarysailor/test
        action: test
        settings_file: '["examples/settings.yml","examples/settings-clear.yml"]'
        fail_on_diff: false

  action-integration-testing:
    name: Action Integration Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Update action.yml to use dockerfile
        uses: rmeneely/update-yaml@v1
        with:
          infile: action.yml
          varlist: "runs.image=Dockerfile"

      - name: cat action.yml
        run: cat action.yml

      - name: Checking ${{ matrix.repo }} against ${{ fromJSON(matrix.settings_file)[0] }}
        id: test-check-action
        if: contains(fromJSON('["check","test"]'), matrix.action) 
        uses: ./
        with:
          token: ${{ secrets.THIS_PAT || github.token }}
          repo: ${{ matrix.repo }}
          settings_file: ${{ fromJSON(matrix.settings_file)[0] }}
          action: check
          fail_on_diff: ${{ matrix.fail_on_diff }}
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}

      - name: Applying ${{ fromJSON(matrix.settings_file)[0] }} to ${{ matrix.repo }}
        id: test-apply-action
        if: matrix.action == 'test'
        uses: ./
        with:
          token: ${{ secrets.THIS_PAT || github.token }}
          repo: ${{ matrix.repo }}
          settings_file: ${{ fromJSON(matrix.settings_file)[0] }}
          action: apply
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}

      - name: Applying ${{ fromJSON(matrix.settings_file)[1] }} to ${{ matrix.repo }}
        id: undo-apply-action
        if: matrix.action == 'test'
        uses: ./
        with:
          token: ${{ secrets.THIS_PAT || github.token }}
          repo: ${{ matrix.repo }}
          settings_file: ${{ fromJSON(matrix.settings_file)[1] }}
          action: apply

      - name: Checking ${{ matrix.repo }} against ${{ fromJSON(matrix.settings_file)[0] }}
        id: final-check-action
        if: matrix.action == 'test'
        uses: ./
        with:
          token: ${{ secrets.THIS_PAT || github.token }}
          repo: ${{ matrix.repo }}
          settings_file: ${{ fromJSON(matrix.settings_file)[1] }}
          action: check
          fail_on_diff: true

      - name: Check outputs
        run: |
          test "${{ steps.test-check-action.outputs.result }}" == "Check passed"
          test "${{ steps.final-check-action.result || 'Check passed' }}" == "Check passed"
