# Tests athe github action on each push
name: Action Integration Test
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/action-integration.yml'
      - 'action.yml'
      - 'Dockerfile'
      - '.github/scripts/replace_inputs.sh'
      - '**/*.py'

  pull_request_target:
    paths:
      - '.github/workflows/action-integration.yml'
      - 'action.yml'
      - 'Dockerfile'
      - '**/*.py'

jobs:
  action-integration-testing:
    name: Action Integration Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Update action.yml to use dockerfile
        uses: rmeneely/update-yaml@v1
        with:
          infile: action.yml
          varlist: "runs.image=Dockerfile"
      - name: cat action.yml
        run: cat action.yml
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          token: ${{ secrets.THIS_PAT || github.token }}
          action: "check"
      - name: Check outputs
        run: |
          test "${{ steps.test-action.outputs.result }}" == "Check passed"
