name: Generate Docs
on:
  push:
  pull_request:
jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v4.1.6
        # https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs

      - name: Run doc generation
        uses: npalm/action-docs-action@v3.1.1

      - name: Commit doc changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "docs: automated doc update"
          file_pattern: README.md
