name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/python-ci.yml'
      - 'action.yml'
      - '.pre-commit-config.yaml'
      - 'package-requirements.txt'
      - 'pyproject.toml'
      - poetry.lock
      - '**/*.py'
      - '**/*.md'
  pull_request:
    paths:
      - '.github/workflows/python-ci.yml'
      - 'action.yml'
      - '.pre-commit-config.yaml'
      - 'package-requirements.txt'
      - 'pyproject.toml'
      - poetry.lock
      - '**/*.py'
      - '**/*.md'

jobs:
  python-ci:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.11", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.11", os: "ubuntu-latest", session: "safety" }
          # - { python: "3.11", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.11", os: "ubuntu-latest", session: "tests" }

    env:
      NOXSESSION: ${{ matrix.session }}
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
      GITHUB_SERVER_URL: ${{ github.server_url }}
      INPUT_TOKEN: ${{ github.token }}  #${{ secrets.THIS_PAT }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.6

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: |
          pip install --constraint=package-requirements.txt pip
          pip --version

      - name: Upgrade pip in virtual environments
        shell: python
        run: |
          import os
          import pip

          with open(os.environ["GITHUB_ENV"], mode="a") as io:
              print(f"VIRTUALENV_PIP={pip.__version__}", file=io)

      - name: Install package-requirements
        run: |
          pip install --upgrade -r package-requirements.txt
          poetry --version
          nox --version

      - name: Compute pre-commit cache key
        if: matrix.session == 'pre-commit'
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import sys
          import os

          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = "${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f"result={result}\n")

      - name: Restore pre-commit cache
        uses: actions/cache@v4.0.2
        if: matrix.session == 'pre-commit'
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.pre-commit-cache.outputs.result }}-

      - name: Run Nox
        run: |
          nox --force-color --python=${{ matrix.python }}

      - name: Upload coverage data
        if: always() && matrix.session == 'tests'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverage-data
          path: ".coverage.*"

      - name: Upload documentation
        if: matrix.session == 'docs-build'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: docs
          path: docs/_build

  coverage:
    runs-on: ubuntu-latest
    needs: python-ci
    steps:
      - name: Download coverage data
        uses: actions/download-artifact@v4.1.8
        with:
          name: coverage-data

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./**/.coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: console
          thresholds: '60 80'

      # - name: Upload coverage report
      #   uses: codecov/codecov-action@v3.1.6
      #   with:
      #     files: .coverage.xml
      #     verbose: true
