on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    if: github.repository_owner == 'actuarysailor'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.1
        with:
          token: ${{ secrets.THIS_PAT }}
          manifest-file: .github/.release-please-manifest.json
