# Runs after release-please creates a new release
# Builds and pushes the docker images for the release
name: Release Docker Images
on:
  release:
    types: [released]
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release-docker-images.yml'

permissions:
  packages: write

jobs:
  build-and-push-dockerimage:
    name: Buld and push dockerimage
    if: github.repository_owner == 'actuarysailor'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}  #${{ secrets.THIS_PAT }}

      - name: Docker metadata
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref_name }}
            # minimal (short sha)
            type=sha,prefix=
            # full length sha
            type=sha,format=long,prefix=

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ github.token }}  #${{ secrets.THIS_PAT }}
