name: Test Docker Image Build

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - pyproject.toml
      - '.github/scripts/replace_inputs.sh'
      - '**/*.py'
  pull_request:
    paths:
      - 'Dockerfile'
      - pyproject.toml
      - '.github/scripts/replace_inputs.sh'
      - '**/*.py'

jobs:
  test-docker-image:
    name: Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.6

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      # The build runs some tests on the built binary to make sure it works as part of its build
      - name: Test Build
        id: docker_build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
